### PR TITLE
resolve "welcome email for subgroup creators" 

### LINKED ISSUE #510: welcome email for subgroup creators [2]
# Acceptance Criteria

GIVEN I am an organizer who just created a subgroup using the form in #503 
* THEN I should receive a welcome email with contents as defined below

# Definitions
* welcome email will contain following content:
 * here's where to log in to admin your group
 * remember, here's the URL for the public signup page for your group, pass it around.
 * email help@affinity.works to ask for help if you're stuck

### PR DESCRIPTION
**Pull request by aguestuser**
this (almost) resolves #510 

# Notes

* I created a good-enough[1] secrets management system to manage the mailgun credentials for it so i could auth with mailgun locally
* I made a mailer to use upon completion of the form, which the rails console, `ActiveMailer::BaseDeliveries`, and our test suite seem to think sends me an email after I fill out the form. Only I never actually receive that email after filling out the form. =(
* Regardless, even if that was a local dev env issue (which we *must* fix to keep working on this), we have a blocking issue with configuring the hostname for URLs to be sent out in emails on prod, since these will differ (1) between affinityworks prod and swingleft prod and (2) across all review apps

For notes on how to resolve both of the above blockers see: 

https://github.com/affinityworks/main/blob/8f13c486cd56b3bd687d76c95487b43a57791bab/config/environments/development.rb#L51-L66

# Screenshots

**WTF! Why doesn't this actually send???**

action-mailer-thinks-it-sent

[1] "good enough" means there is now an `.env` file that gets read by the `dotenv` gemfile into the environment at runtime. the `.env` file is gitignored, but there is an encrypted versoin `.env.gpg` encrypted to a whitelisted set of dev pgp keys

### CODE REVIEW

**Comment by aguestuser** [comment]
ps, for future debuggers, futzing around with some stuff (moving the action mailerconfig back outside the `Rails.application.configure do` block -- which btw, we should *not* have to do), i get fun new SSL errors that look like this:

ssl-error

and point to fun-looking discussions like these:

* https://stackoverflow.com/questions/16016137/an-error-occurred-while-sending-mail-ssl-connect-returned-1-errno-0-state-sslv2
* https://stackoverflow.com/questions/30235156/ssl-connect-returned-1-errno-0-state-sslv2-v3-read-server-hello-a-unknown-protoc
* https://github.com/atech/postal/issues/428

have fun! ;P

**Comment by Matt-Holland** [comment]
Note on the "what is my hostname" issue (potentially naive):
What if we just set an env var in the "config vars" section of the Heroku admin, same place where we set the Facebook API key, MAILGUN_SMTP_LOGIN, etc.? AFAIK these are persistent between deployments, so we only need to set them once for prod and swingleft and staging. As for the review apps, it's not a big deal to manually set that if you really need it in order to test a review app (which most of the time, we won't need).

**Comment by aguestuser** [comment]
not naive. that's about the solution i'd imagine to that particular problem. more specifically, i'd do something like this in `config/network.yml` (which doesn't yet exist):

```yaml
default: &default
  hostname: 'localhost'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  hostname: <%= ENV['HOSTNAME'] =%>
```

and then invoke it wherever we needed it with `Rails.configuration.network.fetch('hostname')`

**Comment by aguestuser** [comment]
now as for the more immediate and vexing problem: why the heck won't these emails that say they're sending actually send?

**Comment by Matt-Holland** [comment]
Also on the SSL error: I am remembering now that when we had problems with the "forgot my password email" before, it was related to changing the name of the app from advocacycommons to affinity, and I _think_ the implication was that the certificate was no longer valid? Or else that the domain wasn't registered with Mailgun. 
And I'm also thinking about the fact that sending email *does* already work when clicking the "forgot password" link from Prod, but *NOT* from staging, which logs an error that this domain is not signed up with Mailgun.
I wonder if the existing code WOULD "just work" if it was running on Prod?

**Comment by aguestuser** [comment]
hmmm... would possibly just work. but we would have no confidence before deploying it. (and would need to roll back if it was broken.) also suggests we likely haven't figured out certs for swing left mailgun setup either? meaning it might work on affinityworks prod but break on swingleft prod?

**Comment by aguestuser** [comment]
in any case, being able to confidently test emails in some environment other than prod seems like a necessary requirement of our toolchain/build pipeline. else: how will we ever assess how to fix SSL errors and such if we don't have an environment in which it is both safe but also possible to conduct trial and error?

**Comment by aguestuser** [comment]
but i am curious if you can get emails to send in any heroku-hosted environment.

**Comment by aguestuser** [comment]
also gonna note (for friday time allocation): there are a few very low-hanging fruit cards hanging out just behind this one. might make sense to clear the deck of those before circling back to this, which is deep and thorny for sure.

**Comment by Matt-Holland** [comment]
Yes we have to figure out the certs, if that's the problem -- I'm just suggesting a direction where the answer might lie. As to "getting email to work", just a reminder that it _already does work_. Just use the "forgot password" feature on prod!

**Comment by aguestuser** [comment]
sorry, i don't think i was specific enough with my language as judging by: "As to "getting email to work", just a reminder that it already does work." 

when i said "email" i am refering to the email i have been focused on all day today. (in my head no other emails exist. this is the only one i've been thinking about, and it doesn't appear to send locally.)

so i meant to say: can you test *this* email on some heroku server to see if it works?

**Comment by aguestuser** [comment]
speaking of which, it would also be an interesting test to see if the retrieve password email is broken locally. (if your hypothesis about certs is right, i would expect it to be? which is 1. good for being able to move this ticket, 2. not confidence-inspiring for being able to develop the app -- but fixing that can be a tech task that we prioritize alongside ongoing feature work.)

as to fixing our certs. that's something i can definitely do and have done before. just won't likely have the bandwidth to do next week.

**Comment by Matt-Holland** [comment]
Running master locally and trying the retrieve password function gives the same result that you are seeing with your thing: the logs make is *appear* that everything worked fine, no error message, but nothing actually happens as far as sending email.
However if you run the review app for this PR and try to get the password reset, you DO get an error message:
```Errno::ECONNREFUSED (Connection refused - connect(2) for nil port 25):```
I thought that "port 25" looked weird, so I checked the ```config/environments/development.rb``` file, which includes ```     :port           => ENV['MAILGUN_SMTP_PORT'],```. However, that ENV didn't appear to be set in the config-vars for the review app. So, I copied over all the mailgun-related config-vars from Production into the review app. That DID succeed in changing the port; now the error message when you try to retrieve your password is:
```Errno::ECONNREFUSED (Connection refused - connect(2) for nil port 587):```
Although clearly "nil" is not right -- seems like we're supposed to be providing a hostname or an IP address there which isn't getting there?
I don't know if this will point toward the core issue or not, but it seems to be in the general direction maybe...

**Comment by Matt-Holland** [comment]
another clue, from the Mailgun logs. An example log line for a message which never made it through:

```      "message": "4.1.8 <bounce+452bcf.974028-aguestuser=riseup.net@mg.affinity.works>: Sender address rejected: Domain not found",```

**Comment by Matt-Holland** [comment]
Ok, after manually setting all the MAILGUN Env vars in the Config section for the review app, I now see the ```OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=unknown state: unknown protocol):``` error that Austin was talking about. Hmmm.

**Comment by Matt-Holland** [comment]
I removed the SSL requirement, and now 1) the password reset email DOES work from the review app, and 2) I do now see that the "email the creator after subgroup creation" job is put into the redis queue -- watching redis monitor I see:
```"rpush" "resque:queue:mailers" "{\"class\":\"ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"7624fae6-8823-43fc-a371-3e2122b8ac84\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"OrganizerMailer\",\"new_subgroup_email\",\"deliver_now\",{\"_aj_globalid\":\"gid://advocacy-commons/Person/125\"},{\"_aj_globalid\":\"gid://advocacy-commons/Group/6\"},{\"_aj_globalid\":\"gid://advocacy-commons/SignupForm/3\"}],\"locale\":\"en\"}]}"```

...however the email still never arrives, _and_ I see nothing in the Mailgun log. Therefore the problem is something to do with the execution of the job which gets put into Redis, and which isn't the same as the SSL problem which was preventing the password reset from working...

**Comment by aguestuser** [comment]
@Matt-Holland can't look at this in-depth but one thing you might want to try is calling `.deliver_now` instead of `.deliver_later` in the `subgroups_controller` here:

https://github.com/affinityworks/main/blob/8f13c486cd56b3bd687d76c95487b43a57791bab/app/controllers/subgroups_controller.rb#L19

this would make the app send the email immediately on the main thread instead of queuing it to be sent in the background. as a general principle, it's a bad idea to do this in production. but as a debugging step, it might help you determine whether it's something about our resque/redis setup that is causing the issue.

**Comment by aguestuser** [comment]
also, in case it's helpful to eliminate variables as to what's causing the problem, i changed the action mailer config in this commit. (note: the way i did it is the standard way, so i'd be surprised if doing it the way i replaced fixes anything, but leaving this here in case it's a useful breadcrumb):

https://github.com/affinityworks/main/pull/520/commits/7b4dcee524e3b54bedea661d21ca61179b9766e9

**Comment by Matt-Holland** [comment]
...and when I try to run the job manually, with ```OrganizerMailer.new_subgroup_email(matt, subgroup, form).deliver_now``` (where i have previously set the values for matt, subgroup and form to the right objects), I get:
```Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 25```
So, that "nil" is supposed to be "smtp.mailgun.org", I'm pretty sure, and port 25 is supposed to be port 587... so it feels like somehow the configuration settings are not getting picked up?

**Comment by aguestuser** [comment]
Behold -- this email was sent to me from a review app on heroku!

welcome-email-finallly-works

I have documented (most of) the toolchain gotchas in the README, and -- as I could not imagine any possible further verification steps having verified this ticket to DEATH at this point -- I am going to merge this PR and promote to production.

**Comment by aguestuser** [comment]
^^ @Matt-Holland

**Pull request merged**
